/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type TaskStatus = "archived" | "pending" | "publish";

export type TaskType = "offline" | "online";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserGender = "female" | "male" | "unknown";

export type UserRole = "admin" | "experimenter" | "participant";

export interface AuthSession {
  create_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: string;
  last_used_at: Timestamp;
  user: string;
}

export interface Task {
  create_at: Generated<Timestamp>;
  desc: string;
  id: Generated<string>;
  name: string;
  owner: string;
  status: Generated<TaskStatus>;
  type: TaskType;
}

export interface TaskRecord {
  create_at: Timestamp;
  data: Json;
  session: string;
}

export interface TaskSession {
  end_at: Timestamp | null;
  id: Generated<string>;
  start_at: Timestamp;
  task: string;
}

export interface TaskSessionParticipantRel {
  participant: string;
  session: string;
}

export interface User {
  birthday: Timestamp;
  create_at: Generated<Timestamp>;
  email: string;
  gender: UserGender;
  id: Generated<string>;
  name: string;
  phone: string | null;
  pwd: string;
  role: UserRole;
}

export interface DB {
  auth_session: AuthSession;
  task: Task;
  task_record: TaskRecord;
  task_session: TaskSession;
  task_session_participant_rel: TaskSessionParticipantRel;
  user: User;
}
